name: Test My Action

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run My Action
        uses: josephgultekin/ts-github-action@main
        with:
          name: "Joseph Gultekin"
    
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm test
      - run: node --version

      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: echo "The ${{github.repository}} has been cloned to the runner"
      - run: echo "The workflow is now ready to test your code on the runner"


